micronaut:
  application:
    name: demo
  executors:
    io:
      type: FIXED
      n-threads: 100
      number-of-threads: 100
      virtual: false
  http:
    client:
      # read-timeout: 30s        ## <<-- Seems to work
    services:
      httpbun:
        url: http://127.0.0.1/
        read-timeout: 30s        ## <<-- Doesn't seem to work
        prefer-native-transport: true
        num-of-threads: 10
        pool:
          enabled: true
          max-connections: 25
